/**
 * Demo provider snapshots for visual proof/comparison screenshots.
 *
 * These mimic realistic usage data across multiple providers so the tray
 * panel can be compared against a fully-populated macOS CodexBar panel.
 * Only used when `VITE_DEMO_PROVIDERS=1` is set at build time.
 */
import type { ProviderUsageSnapshot } from "../types/bridge";

export const DEMO_ENABLED = import.meta.env.VITE_DEMO_PROVIDERS === "1";

const now = new Date().toISOString();

export const DEMO_PROVIDERS: ProviderUsageSnapshot[] = [
  {
    providerId: "antigravity",
    displayName: "Antigravity",
    primaryLabel: "Session",
    primary: {
      usedPercent: 100,
      remainingPercent: 0,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "Resets in 12m",
      isExhausted: true,
      reservePercent: null,
      reserveDescription: null,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    cost: null,
    planName: "Team",
    accountEmail: "peter@steipete.com",
    sourceLabel: "CLI",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: "steipete",
    trayStatusLabel: "Exhausted",
  },
  {
    providerId: "copilot",
    displayName: "GitHub Copilot",
    primaryLabel: "Monthly",
    primary: {
      usedPercent: 89,
      remainingPercent: 11,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "Resets in 2d 5h",
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    cost: null,
    planName: "Business",
    accountEmail: "peter@github.com",
    sourceLabel: "OAuth",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: "steipete",
    trayStatusLabel: null,
  },
  {
    providerId: "claude",
    displayName: "Claude",
    primaryLabel: "Session",
    primary: {
      usedPercent: 72,
      remainingPercent: 28,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "Resets in 1h 23m",
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondaryLabel: "Weekly",
    secondary: {
      usedPercent: 45,
      remainingPercent: 55,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "Resets in 4d 12h",
      isExhausted: false,
      reservePercent: 33,
      reserveDescription: "Lasts until reset",
    },
    modelSpecific: null,
    tertiary: null,
    cost: null,
    planName: "Pro",
    accountEmail: "peter@codexbar.dev",
    sourceLabel: "Cookie",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
  {
    providerId: "codex",
    displayName: "Codex",
    primaryLabel: "Session",
    primary: {
      usedPercent: 0,
      remainingPercent: 100,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "Resets in 5h",
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondaryLabel: "Weekly",
    secondary: {
      usedPercent: 59,
      remainingPercent: 41,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "Resets in 12h 41m",
      isExhausted: false,
      reservePercent: 33,
      reserveDescription: "Lasts until reset",
    },
    modelSpecific: null,
    tertiary: null,
    cost: null,
    planName: "Plus",
    accountEmail: "peter@codexbar.dev",
    sourceLabel: "CLI",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
  {
    providerId: "claude-err",
    displayName: "Claude",
    primary: {
      usedPercent: 0,
      remainingPercent: 0,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: null,
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    cost: null,
    planName: null,
    accountEmail: null,
    sourceLabel: "Cookie",
    updatedAt: now,
    error: "No available fetch strategy for claude.",
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
  {
    providerId: "cursor-err",
    displayName: "Cursor",
    primary: {
      usedPercent: 0,
      remainingPercent: 0,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: null,
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    cost: null,
    planName: null,
    accountEmail: null,
    sourceLabel: "Cookie",
    updatedAt: now,
    error: "No Cursor session found. Please log in to cursor.com in Safari, Chrome, Microsoft Edge, Brave, Arc, Dia, ChatGPT Atlas, Chromium, Helium, Vivaldi, Firefox, Zen, Chrome Beta, Chro…",
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
];
