/**
 * Demo provider snapshots for visual proof/comparison screenshots.
 *
 * These mimic realistic usage data across multiple providers so the tray
 * panel can be compared against a fully-populated macOS CodexBar panel.
 * Only used when `VITE_DEMO_PROVIDERS=1` is set at build time.
 */
import type { ProviderUsageSnapshot } from "../types/bridge";

export const DEMO_ENABLED = import.meta.env.VITE_DEMO_PROVIDERS === "1";

const now = new Date().toISOString();

export const DEMO_PROVIDERS: ProviderUsageSnapshot[] = [
  {
    providerId: "antigravity",
    displayName: "Antigravity",
    primary: {
      usedPercent: 100,
      remainingPercent: 0,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "Resets in 12m",
      isExhausted: true,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    cost: null,
    planName: "Team",
    accountEmail: "peter@steipete.com",
    sourceLabel: "CLI",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: "steipete",
    trayStatusLabel: "Exhausted",
  },
  {
    providerId: "copilot",
    displayName: "GitHub Copilot",
    primary: {
      usedPercent: 89,
      remainingPercent: 11,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "Monthly · 11% left",
      isExhausted: false,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    cost: null,
    planName: "Business",
    accountEmail: "peter@github.com",
    sourceLabel: "OAuth",
    updatedAt: now,
    error: null,
    pace: {
      stage: "far_ahead",
      deltaPercent: 24.0,
      willLastToReset: false,
      etaSeconds: 172800,
      expectedUsedPercent: 65.0,
      actualUsedPercent: 89.0,
    },
    accountOrganization: "steipete",
    trayStatusLabel: null,
  },
  {
    providerId: "claude",
    displayName: "Claude",
    primary: {
      usedPercent: 72,
      remainingPercent: 28,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "Resets in 1h 23m",
      isExhausted: false,
    },
    secondary: {
      usedPercent: 45,
      remainingPercent: 55,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "Monthly · 55% left",
      isExhausted: false,
    },
    modelSpecific: null,
    tertiary: null,
    cost: null,
    planName: "Pro",
    accountEmail: "peter@codexbar.dev",
    sourceLabel: "Cookie",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
  {
    providerId: "codex",
    displayName: "Codex",
    primary: {
      usedPercent: 34,
      remainingPercent: 66,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "Monthly · 66% left",
      isExhausted: false,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    cost: {
      used: 12.40,
      limit: 50.0,
      remaining: 37.60,
      currencyCode: "USD",
      period: "Monthly",
      resetsAt: null,
      formattedUsed: "$12.40",
      formattedLimit: "$50.00",
    },
    planName: "Plus",
    accountEmail: "peter@codexbar.dev",
    sourceLabel: "CLI",
    updatedAt: now,
    error: null,
    pace: {
      stage: "on_track",
      deltaPercent: 2.1,
      willLastToReset: true,
      etaSeconds: null,
      expectedUsedPercent: 32.0,
      actualUsedPercent: 34.0,
    },
    accountOrganization: null,
    trayStatusLabel: null,
  },
];
