/**
 * Demo provider snapshots for visual proof/comparison screenshots.
 *
 * These mimic realistic usage data across multiple providers so the tray
 * panel can be compared against a fully-populated macOS CodexBar panel.
 * Only used when `VITE_DEMO_PROVIDERS=1` is set at build time.
 */
import type { ProviderUsageSnapshot, RateWindowSnapshot } from "../types/bridge";

export const DEMO_ENABLED = import.meta.env.VITE_DEMO_PROVIDERS === "1";

const now = new Date().toISOString();

const EMPTY_RATE: RateWindowSnapshot = {
  usedPercent: 0,
  remainingPercent: 0,
  windowMinutes: null,
  resetsAt: null,
  resetDescription: null,
  isExhausted: false,
  reservePercent: null,
  reserveDescription: null,
};

function makeGridProvider(id: string, name: string, usedPct: number): ProviderUsageSnapshot {
  return {
    providerId: id,
    displayName: name,
    primaryLabel: "Monthly",
    primary: {
      usedPercent: usedPct,
      remainingPercent: 100 - usedPct,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: `${Math.floor(Math.random() * 28 + 1)}d`,
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: "Free",
    accountEmail: null,
    sourceLabel: "CLI",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  };
}

export const DEMO_PROVIDERS: ProviderUsageSnapshot[] = [
  // ── Featured providers (full card data) ──
  {
    providerId: "codex",
    displayName: "Codex",
    primaryLabel: "Session",
    primary: {
      usedPercent: 0,
      remainingPercent: 100,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "5h",
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondaryLabel: "Weekly",
    secondary: {
      usedPercent: 59,
      remainingPercent: 41,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "12h 41m",
      isExhausted: false,
      reservePercent: 33,
      reserveDescription: "Lasts until reset",
    },
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: "Team",
    accountEmail: "chatgpt.com.hp9wp@southernwind.xyz",
    sourceLabel: "CLI",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
  {
    providerId: "claude",
    displayName: "Claude",
    primaryLabel: "Session",
    primary: {
      usedPercent: 72,
      remainingPercent: 28,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "1h 23m",
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondaryLabel: "Weekly",
    secondary: {
      usedPercent: 45,
      remainingPercent: 55,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "4d 12h",
      isExhausted: false,
      reservePercent: 33,
      reserveDescription: "Lasts until reset",
    },
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: "Pro",
    accountEmail: null,
    sourceLabel: "Cookie",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
  {
    providerId: "antigravity",
    displayName: "Antigravity",
    primaryLabel: "Session",
    primary: {
      usedPercent: 100,
      remainingPercent: 0,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "12m",
      isExhausted: true,
      reservePercent: null,
      reserveDescription: null,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: "Team",
    accountEmail: null,
    sourceLabel: "CLI",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: "steipete",
    trayStatusLabel: "Exhausted",
  },
  {
    providerId: "copilot",
    displayName: "GitHub Copilot",
    primaryLabel: "Monthly",
    primary: {
      usedPercent: 89,
      remainingPercent: 11,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "2d 5h",
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: "Business",
    accountEmail: null,
    sourceLabel: "OAuth",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: "steipete",
    trayStatusLabel: null,
  },
  // ── Error providers ──
  {
    providerId: "claude-err",
    displayName: "Claude",
    primary: EMPTY_RATE,
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: null,
    accountEmail: null,
    sourceLabel: "Cookie",
    updatedAt: now,
    error: "No available fetch strategy for claude.",
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
  {
    providerId: "cursor-err",
    displayName: "Cursor",
    primary: EMPTY_RATE,
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: null,
    accountEmail: null,
    sourceLabel: "Cookie",
    updatedAt: now,
    error: "No Cursor session found. Please log in to cursor.com in Safari, Chrome, Microsoft Edge, Brave, Arc, Dia, ChatGPT Atlas, Chromium, Helium, Vivaldi, Firefox, Zen, Chrome Beta, Chro\u2026",
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
  // ── Grid-only providers (fill out icon grid like macOS) ──
  makeGridProvider("opencode", "OpenCode", 15),
  makeGridProvider("openai", "OpenAI", 42),
  makeGridProvider("alibaba", "Alibaba", 8),
  makeGridProvider("droid", "Droid", 61),
  makeGridProvider("gemini", "Gemini", 35),
  makeGridProvider("copilot2", "Copilot", 22),
  makeGridProvider("zai", "z.ai", 50),
  makeGridProvider("minimax", "MiniMax", 73),
  makeGridProvider("kimi", "Kimi", 18),
  makeGridProvider("kilo", "Kilo", 29),
  makeGridProvider("kiro", "Kiro", 5),
  makeGridProvider("vertex", "Vertex AI", 38),
  makeGridProvider("augment", "Augment", 55),
  makeGridProvider("jetbrains", "JetBrains", 12),
  makeGridProvider("kimi-k2", "Kimi K2", 44),
  makeGridProvider("amp", "Amp", 67),
  makeGridProvider("ollama", "Ollama", 3),
  makeGridProvider("warp", "Warp", 48),
  makeGridProvider("perplexity", "Perplexity", 20),
];
